version: "3.7"
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_HOME=/neo4j
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    volumes:
      - ./neo4j/data:/data:rw
      - ./neo4j:/neo4j:rw
      - ./neo4j/import:/var/lib/neo4j/import:rw
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
        max-file: "2"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    restart: unless-stopped

  hello_world:
    build:
      context: ./
      dockerfile: ./src/hello_world/Dockerfile
    container_name: hello_world
    environment:
      - CONFIG_NAME=settings.conf
    depends_on:
      - neo4j
    restart: "no"

  neo_rest:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    container_name: neo_rest
    restart: unless-stopped
    ports:
      - "5000:5000"
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    container_name: ui
    restart: unless-stopped
    #    environment:
    #      - SERVER_URL=neo_rest:5000
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: tx_net

